// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.bruker.paser.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Candidate : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Candidate\",\"namespace\":\"com.bruker.paser.avro\",\"fields\":" +
				"[{\"name\":\"rank\",\"doc\":\"ranking of the candidate for the given precursor by Xcorr" +
				"; Current SQT M Rank by Xcorr \",\"type\":\"int\"},{\"name\":\"stripped_peptide\",\"doc\":\"" +
				"string of N characters denoting the stripped amino-acid sequence; Current SQT M " +
				"part of Sequence\",\"type\":\"string\"},{\"name\":\"ptms\",\"doc\":\"array of ptms for this " +
				"candidate; Current SQT M part of Sequence. PTMs are encoded like in sqt file, e." +
				"g. (79.966331). Six digits are mandatory\",\"type\":{\"type\":\"array\",\"items\":\"string" +
				"\"}},{\"name\":\"ptm_locations\",\"doc\":\"array of indices denoting the location of a p" +
				"tm. There are two special indices\\n * -1 denotes N-term modification\\n *  N deno" +
				"tes C-term modification; Current SQT M part of Sequence\",\"type\":{\"type\":\"array\"," +
				"\"items\":\"int\"}},{\"name\":\"leading_AA\",\"doc\":\"string of 1-3 characters denoting th" +
				"e AA seqeunce N-terminal of candidate peptide. Protein N-terminus denoted by \'-\'" +
				"; Current SQT M part of Sequence\",\"type\":\"string\"},{\"name\":\"tailing_AA\",\"doc\":\"s" +
				"tring of 1-3 characters denoting the AA seqeunce C-terminal of candidate peptide" +
				". Protein C-terminus denoted by \'-\'; Current SQT M part of Sequence\",\"type\":\"str" +
				"ing\"},{\"name\":\"Xcorr\",\"doc\":\"Xcorr for that candidate; Current SQT M Xcorr\",\"typ" +
				"e\":\"float\"},{\"name\":\"deltaCN\",\"doc\":\"deltaCN for that candidate; Current SQT M D" +
				"eltaCN\",\"type\":\"float\"},{\"name\":\"calc_mass\",\"doc\":\"Calcualted mass for that cand" +
				"idate; Current SQT M Calc_Mass\",\"type\":\"float\"},{\"name\":\"matched_ions\",\"doc\":\"Nu" +
				"mber of matched ions for that candidate; Current SQT M Matched Ions\",\"type\":\"int" +
				"\"},{\"name\":\"predicted_ooK0\",\"doc\":\"predicted inverse mobility - 1/K0 - of the ca" +
				"ndidate; Current SQT M Predicted_CCS\",\"type\":\"double\"},{\"name\":\"TIMScore\",\"doc\":" +
				"\"TIMScore for that candidate ; Current SQT M TIMScore\",\"type\":\"float\"},{\"name\":\"" +
				"locus\",\"doc\":\"array of locus for a candidate\",\"type\":{\"type\":\"array\",\"items\":{\"t" +
				"ype\":\"record\",\"name\":\"Locus\",\"namespace\":\"com.bruker.paser.avro\",\"fields\":[{\"nam" +
				"e\":\"locus_name\",\"doc\":\"Accession number of locus; Current SQT L Locus_name\",\"typ" +
				"e\":\"string\"},{\"name\":\"locus_peptide_index\",\"doc\":\"peptide index in protein seque" +
				"nce; Current SQT L peptide_index in protein\",\"type\":\"int\"}]}}}]}");
		/// <summary>
		/// ranking of the candidate for the given precursor by Xcorr; Current SQT M Rank by Xcorr 
		/// </summary>
		private int _rank;
		/// <summary>
		/// string of N characters denoting the stripped amino-acid sequence; Current SQT M part of Sequence
		/// </summary>
		private string _stripped_peptide;
		/// <summary>
		/// array of ptms for this candidate; Current SQT M part of Sequence. PTMs are encoded like in sqt file, e.g. (79.966331). Six digits are mandatory
		/// </summary>
		private IList<System.String> _ptms;
		/// <summary>
		/// array of indices denoting the location of a ptm. There are two special indices
		/// * -1 denotes N-term modification
		/// *  N denotes C-term modification; Current SQT M part of Sequence
		/// </summary>
		private IList<System.Int32> _ptm_locations;
		/// <summary>
		/// string of 1-3 characters denoting the AA seqeunce N-terminal of candidate peptide. Protein N-terminus denoted by '-'; Current SQT M part of Sequence
		/// </summary>
		private string _leading_AA;
		/// <summary>
		/// string of 1-3 characters denoting the AA seqeunce C-terminal of candidate peptide. Protein C-terminus denoted by '-'; Current SQT M part of Sequence
		/// </summary>
		private string _tailing_AA;
		/// <summary>
		/// Xcorr for that candidate; Current SQT M Xcorr
		/// </summary>
		private float _Xcorr;
		/// <summary>
		/// deltaCN for that candidate; Current SQT M DeltaCN
		/// </summary>
		private float _deltaCN;
		/// <summary>
		/// Calcualted mass for that candidate; Current SQT M Calc_Mass
		/// </summary>
		private float _calc_mass;
		/// <summary>
		/// Number of matched ions for that candidate; Current SQT M Matched Ions
		/// </summary>
		private int _matched_ions;
		/// <summary>
		/// predicted inverse mobility - 1/K0 - of the candidate; Current SQT M Predicted_CCS
		/// </summary>
		private double _predicted_ooK0;
		/// <summary>
		/// TIMScore for that candidate ; Current SQT M TIMScore
		/// </summary>
		private float _TIMScore;
		/// <summary>
		/// array of locus for a candidate
		/// </summary>
		private IList<com.bruker.paser.avro.Locus> _locus;
		public virtual Schema Schema
		{
			get
			{
				return Candidate._SCHEMA;
			}
		}
		/// <summary>
		/// ranking of the candidate for the given precursor by Xcorr; Current SQT M Rank by Xcorr 
		/// </summary>
		public int rank
		{
			get
			{
				return this._rank;
			}
			set
			{
				this._rank = value;
			}
		}
		/// <summary>
		/// string of N characters denoting the stripped amino-acid sequence; Current SQT M part of Sequence
		/// </summary>
		public string stripped_peptide
		{
			get
			{
				return this._stripped_peptide;
			}
			set
			{
				this._stripped_peptide = value;
			}
		}
		/// <summary>
		/// array of ptms for this candidate; Current SQT M part of Sequence. PTMs are encoded like in sqt file, e.g. (79.966331). Six digits are mandatory
		/// </summary>
		public IList<System.String> ptms
		{
			get
			{
				return this._ptms;
			}
			set
			{
				this._ptms = value;
			}
		}
		/// <summary>
		/// array of indices denoting the location of a ptm. There are two special indices
		/// * -1 denotes N-term modification
		/// *  N denotes C-term modification; Current SQT M part of Sequence
		/// </summary>
		public IList<System.Int32> ptm_locations
		{
			get
			{
				return this._ptm_locations;
			}
			set
			{
				this._ptm_locations = value;
			}
		}
		/// <summary>
		/// string of 1-3 characters denoting the AA seqeunce N-terminal of candidate peptide. Protein N-terminus denoted by '-'; Current SQT M part of Sequence
		/// </summary>
		public string leading_AA
		{
			get
			{
				return this._leading_AA;
			}
			set
			{
				this._leading_AA = value;
			}
		}
		/// <summary>
		/// string of 1-3 characters denoting the AA seqeunce C-terminal of candidate peptide. Protein C-terminus denoted by '-'; Current SQT M part of Sequence
		/// </summary>
		public string tailing_AA
		{
			get
			{
				return this._tailing_AA;
			}
			set
			{
				this._tailing_AA = value;
			}
		}
		/// <summary>
		/// Xcorr for that candidate; Current SQT M Xcorr
		/// </summary>
		public float Xcorr
		{
			get
			{
				return this._Xcorr;
			}
			set
			{
				this._Xcorr = value;
			}
		}
		/// <summary>
		/// deltaCN for that candidate; Current SQT M DeltaCN
		/// </summary>
		public float deltaCN
		{
			get
			{
				return this._deltaCN;
			}
			set
			{
				this._deltaCN = value;
			}
		}
		/// <summary>
		/// Calcualted mass for that candidate; Current SQT M Calc_Mass
		/// </summary>
		public float calc_mass
		{
			get
			{
				return this._calc_mass;
			}
			set
			{
				this._calc_mass = value;
			}
		}
		/// <summary>
		/// Number of matched ions for that candidate; Current SQT M Matched Ions
		/// </summary>
		public int matched_ions
		{
			get
			{
				return this._matched_ions;
			}
			set
			{
				this._matched_ions = value;
			}
		}
		/// <summary>
		/// predicted inverse mobility - 1/K0 - of the candidate; Current SQT M Predicted_CCS
		/// </summary>
		public double predicted_ooK0
		{
			get
			{
				return this._predicted_ooK0;
			}
			set
			{
				this._predicted_ooK0 = value;
			}
		}
		/// <summary>
		/// TIMScore for that candidate ; Current SQT M TIMScore
		/// </summary>
		public float TIMScore
		{
			get
			{
				return this._TIMScore;
			}
			set
			{
				this._TIMScore = value;
			}
		}
		/// <summary>
		/// array of locus for a candidate
		/// </summary>
		public IList<com.bruker.paser.avro.Locus> locus
		{
			get
			{
				return this._locus;
			}
			set
			{
				this._locus = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.rank;
			case 1: return this.stripped_peptide;
			case 2: return this.ptms;
			case 3: return this.ptm_locations;
			case 4: return this.leading_AA;
			case 5: return this.tailing_AA;
			case 6: return this.Xcorr;
			case 7: return this.deltaCN;
			case 8: return this.calc_mass;
			case 9: return this.matched_ions;
			case 10: return this.predicted_ooK0;
			case 11: return this.TIMScore;
			case 12: return this.locus;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.rank = (System.Int32)fieldValue; break;
			case 1: this.stripped_peptide = (System.String)fieldValue; break;
			case 2: this.ptms = (IList<System.String>)fieldValue; break;
			case 3: this.ptm_locations = (IList<System.Int32>)fieldValue; break;
			case 4: this.leading_AA = (System.String)fieldValue; break;
			case 5: this.tailing_AA = (System.String)fieldValue; break;
			case 6: this.Xcorr = (System.Single)fieldValue; break;
			case 7: this.deltaCN = (System.Single)fieldValue; break;
			case 8: this.calc_mass = (System.Single)fieldValue; break;
			case 9: this.matched_ions = (System.Int32)fieldValue; break;
			case 10: this.predicted_ooK0 = (System.Double)fieldValue; break;
			case 11: this.TIMScore = (System.Single)fieldValue; break;
			case 12: this.locus = (IList<com.bruker.paser.avro.Locus>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
