// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.bruker.paser.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Locus : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Locus"",""namespace"":""com.bruker.paser.avro"",""fields"":[{""name"":""locus_name"",""doc"":""Accession number of locus; Current SQT L Locus_name"",""type"":""string""},{""name"":""locus_peptide_index"",""doc"":""peptide index in protein sequence; Current SQT L peptide_index in protein"",""type"":""int""}]}");
		/// <summary>
		/// Accession number of locus; Current SQT L Locus_name
		/// </summary>
		private string _locus_name;
		/// <summary>
		/// peptide index in protein sequence; Current SQT L peptide_index in protein
		/// </summary>
		private int _locus_peptide_index;
		public virtual Schema Schema
		{
			get
			{
				return Locus._SCHEMA;
			}
		}
		/// <summary>
		/// Accession number of locus; Current SQT L Locus_name
		/// </summary>
		public string locus_name
		{
			get
			{
				return this._locus_name;
			}
			set
			{
				this._locus_name = value;
			}
		}
		/// <summary>
		/// peptide index in protein sequence; Current SQT L peptide_index in protein
		/// </summary>
		public int locus_peptide_index
		{
			get
			{
				return this._locus_peptide_index;
			}
			set
			{
				this._locus_peptide_index = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.locus_name;
			case 1: return this.locus_peptide_index;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.locus_name = (System.String)fieldValue; break;
			case 1: this.locus_peptide_index = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
