// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.bruker.paser.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class PsmProlucid : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"PsmProlucid\",\"namespace\":\"com.bruker.paser.avro\",\"fields" +
				"\":[{\"name\":\"ms2_id\",\"doc\":\"id of the precursor; monotonically increasing integer" +
				" id of Ms2 spectra; Current SQT S low_scan & high_scan \",\"type\":\"int\"},{\"name\":\"" +
				"parent_id\",\"doc\":\"integer id of the corresponding Ms1 parent frame\",\"type\":\"int\"" +
				"},{\"name\":\"rt\",\"doc\":\"retention time in seconds of the precursor\",\"type\":\"double" +
				"\"},{\"name\":\"ooK0\",\"doc\":\"inverse mobility - 1/K0 - of the precursor; Current SQT" +
				" S Measured_CCS\",\"type\":\"double\"},{\"name\":\"mono_mz\",\"doc\":\"monoisotopic mass per" +
				" charge of the precursor\",\"type\":\"double\"},{\"name\":\"charge\",\"doc\":\"integer units" +
				" of elementary charge of the precursor; Current SQT S Charge\",\"type\":\"int\"},{\"na" +
				"me\":\"processing_time\",\"doc\":\"prolucid processing time in seconds; Current SQT S " +
				"PTime\",\"type\":\"double\"},{\"name\":\"TIC\",\"doc\":\"Total ion current for that spectrum" +
				"; Current SQT S Total_Ion_Int\",\"type\":\"int\"},{\"name\":\"candidates\",\"doc\":\"array o" +
				"f candidates for a prolucid PSMs\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record" +
				"\",\"name\":\"Candidate\",\"namespace\":\"com.bruker.paser.avro\",\"fields\":[{\"name\":\"rank" +
				"\",\"doc\":\"ranking of the candidate for the given precursor by Xcorr; Current SQT " +
				"M Rank by Xcorr \",\"type\":\"int\"},{\"name\":\"stripped_peptide\",\"doc\":\"string of N ch" +
				"aracters denoting the stripped amino-acid sequence; Current SQT M part of Sequen" +
				"ce\",\"type\":\"string\"},{\"name\":\"ptms\",\"doc\":\"array of ptms for this candidate; Cur" +
				"rent SQT M part of Sequence. PTMs are encoded like in sqt file, e.g. (79.966331)" +
				". Six digits are mandatory\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"p" +
				"tm_locations\",\"doc\":\"array of indices denoting the location of a ptm. There are " +
				"two special indices\\n * -1 denotes N-term modification\\n *  N denotes C-term mod" +
				"ification; Current SQT M part of Sequence\",\"type\":{\"type\":\"array\",\"items\":\"int\"}" +
				"},{\"name\":\"leading_AA\",\"doc\":\"string of 1-3 characters denoting the AA seqeunce " +
				"N-terminal of candidate peptide. Protein N-terminus denoted by \'-\'; Current SQT " +
				"M part of Sequence\",\"type\":\"string\"},{\"name\":\"tailing_AA\",\"doc\":\"string of 1-3 c" +
				"haracters denoting the AA seqeunce C-terminal of candidate peptide. Protein C-te" +
				"rminus denoted by \'-\'; Current SQT M part of Sequence\",\"type\":\"string\"},{\"name\":" +
				"\"Xcorr\",\"doc\":\"Xcorr for that candidate; Current SQT M Xcorr\",\"type\":\"float\"},{\"" +
				"name\":\"deltaCN\",\"doc\":\"deltaCN for that candidate; Current SQT M DeltaCN\",\"type\"" +
				":\"float\"},{\"name\":\"calc_mass\",\"doc\":\"Calcualted mass for that candidate; Current" +
				" SQT M Calc_Mass\",\"type\":\"float\"},{\"name\":\"matched_ions\",\"doc\":\"Number of matche" +
				"d ions for that candidate; Current SQT M Matched Ions\",\"type\":\"int\"},{\"name\":\"pr" +
				"edicted_ooK0\",\"doc\":\"predicted inverse mobility - 1/K0 - of the candidate; Curre" +
				"nt SQT M Predicted_CCS\",\"type\":\"double\"},{\"name\":\"TIMScore\",\"doc\":\"TIMScore for " +
				"that candidate ; Current SQT M TIMScore\",\"type\":\"float\"},{\"name\":\"locus\",\"doc\":\"" +
				"array of locus for a candidate\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\"," +
				"\"name\":\"Locus\",\"namespace\":\"com.bruker.paser.avro\",\"fields\":[{\"name\":\"locus_name" +
				"\",\"doc\":\"Accession number of locus; Current SQT L Locus_name\",\"type\":\"string\"},{" +
				"\"name\":\"locus_peptide_index\",\"doc\":\"peptide index in protein sequence; Current S" +
				"QT L peptide_index in protein\",\"type\":\"int\"}]}}}]}}}],\"version\":\"1\"}");
		/// <summary>
		/// id of the precursor; monotonically increasing integer id of Ms2 spectra; Current SQT S low_scan & high_scan 
		/// </summary>
		private int _ms2_id;
		/// <summary>
		/// integer id of the corresponding Ms1 parent frame
		/// </summary>
		private int _parent_id;
		/// <summary>
		/// retention time in seconds of the precursor
		/// </summary>
		private double _rt;
		/// <summary>
		/// inverse mobility - 1/K0 - of the precursor; Current SQT S Measured_CCS
		/// </summary>
		private double _ooK0;
		/// <summary>
		/// monoisotopic mass per charge of the precursor
		/// </summary>
		private double _mono_mz;
		/// <summary>
		/// integer units of elementary charge of the precursor; Current SQT S Charge
		/// </summary>
		private int _charge;
		/// <summary>
		/// prolucid processing time in seconds; Current SQT S PTime
		/// </summary>
		private double _processing_time;
		/// <summary>
		/// Total ion current for that spectrum; Current SQT S Total_Ion_Int
		/// </summary>
		private int _TIC;
		/// <summary>
		/// array of candidates for a prolucid PSMs
		/// </summary>
		private IList<com.bruker.paser.avro.Candidate> _candidates;
		public virtual Schema Schema
		{
			get
			{
				return PsmProlucid._SCHEMA;
			}
		}
		/// <summary>
		/// id of the precursor; monotonically increasing integer id of Ms2 spectra; Current SQT S low_scan & high_scan 
		/// </summary>
		public int ms2_id
		{
			get
			{
				return this._ms2_id;
			}
			set
			{
				this._ms2_id = value;
			}
		}
		/// <summary>
		/// integer id of the corresponding Ms1 parent frame
		/// </summary>
		public int parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				this._parent_id = value;
			}
		}
		/// <summary>
		/// retention time in seconds of the precursor
		/// </summary>
		public double rt
		{
			get
			{
				return this._rt;
			}
			set
			{
				this._rt = value;
			}
		}
		/// <summary>
		/// inverse mobility - 1/K0 - of the precursor; Current SQT S Measured_CCS
		/// </summary>
		public double ooK0
		{
			get
			{
				return this._ooK0;
			}
			set
			{
				this._ooK0 = value;
			}
		}
		/// <summary>
		/// monoisotopic mass per charge of the precursor
		/// </summary>
		public double mono_mz
		{
			get
			{
				return this._mono_mz;
			}
			set
			{
				this._mono_mz = value;
			}
		}
		/// <summary>
		/// integer units of elementary charge of the precursor; Current SQT S Charge
		/// </summary>
		public int charge
		{
			get
			{
				return this._charge;
			}
			set
			{
				this._charge = value;
			}
		}
		/// <summary>
		/// prolucid processing time in seconds; Current SQT S PTime
		/// </summary>
		public double processing_time
		{
			get
			{
				return this._processing_time;
			}
			set
			{
				this._processing_time = value;
			}
		}
		/// <summary>
		/// Total ion current for that spectrum; Current SQT S Total_Ion_Int
		/// </summary>
		public int TIC
		{
			get
			{
				return this._TIC;
			}
			set
			{
				this._TIC = value;
			}
		}
		/// <summary>
		/// array of candidates for a prolucid PSMs
		/// </summary>
		public IList<com.bruker.paser.avro.Candidate> candidates
		{
			get
			{
				return this._candidates;
			}
			set
			{
				this._candidates = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ms2_id;
			case 1: return this.parent_id;
			case 2: return this.rt;
			case 3: return this.ooK0;
			case 4: return this.mono_mz;
			case 5: return this.charge;
			case 6: return this.processing_time;
			case 7: return this.TIC;
			case 8: return this.candidates;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ms2_id = (System.Int32)fieldValue; break;
			case 1: this.parent_id = (System.Int32)fieldValue; break;
			case 2: this.rt = (System.Double)fieldValue; break;
			case 3: this.ooK0 = (System.Double)fieldValue; break;
			case 4: this.mono_mz = (System.Double)fieldValue; break;
			case 5: this.charge = (System.Int32)fieldValue; break;
			case 6: this.processing_time = (System.Double)fieldValue; break;
			case 7: this.TIC = (System.Int32)fieldValue; break;
			case 8: this.candidates = (IList<com.bruker.paser.avro.Candidate>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
